### PR TITLE
fix track changes hook call

### PR DESCRIPTION
**Pull request by asouqi**

### CODE REVIEW

**Review by mbartenev-atypon — APPROVED** [review]

**Comment by mbartenev-atypon** [comment]
@asouqi , is there any specific error that is fixed by that? Something visible in the console or a specific behaviour?

**Comment by asouqi** [comment]
> is there any specific error that is fixed by that? Something visible in the console or a specific behaviour?

this is related to the issue in this [PR](https://github.com/atypon/leanworkflow-dashboard/pull/430#issuecomment-1402860726) when enabling track changes, look at the [view](https://github.com/Atypon-OpenSource/manuscripts-article-editor/blob/master/src/components/track-changes/useEditorStore.ts#L36) in useEditorStore

**Comment by mbartenev-atypon** [comment]
> > is there any specific error that is fixed by that? Something visible in the console or a specific behaviour?
> 
> this is related to the issue in this [PR](https://github.com/atypon/leanworkflow-dashboard/pull/430#issuecomment-1402860726) when enabling track changes, look at the [view](https://github.com/Atypon-OpenSource/manuscripts-article-editor/blob/master/src/components/track-changes/useEditorStore.ts#L36) in useEditorStore

Ah, I see. I added a different fix for it here: https://github.com/Atypon-OpenSource/manuscripts-article-editor/blob/various-fixes-test/src/components/projects/lean-workflow/ManuscriptPageContainerLW.tsx#L173. It look to me that the order of execution has changes with the new react version so I moved the init action to be earlier to avoid any related issues. What do you think?

**Comment by asouqi** [comment]
> It look to me that the order of execution has changes with the new react version so I moved the init action to be earlier to avoid any related issues. What do you think?

that will be better.

**Pull request closed without merging**
