### PR TITLE
LEAN-1334 UIQW-010 - Open Editor with Inspector open on Comments by d…

### PR DESCRIPTION
**Pull request by fwaisi**
…efault

### CODE REVIEW

**Comment by fwaisi** [comment]
> @fwaisi, I see nothing regarding force opening the inspector!

Because it's already opened by default.

**Comment by IslamJMomani** [comment]
> > @fwaisi, I see nothing regarding force opening the inspector!
> 
> Because it's already opened by default.

From what I can see in [this line](https://github.com/Atypon-OpenSource/manuscripts-article-editor/blob/master/src/components/projects/Inspector.tsx#L88), it currently depends on the existence of a suggestion or comment. Are these conditions met in your case?

**Comment by fwaisi** [comment]
> > > @fwaisi, I see nothing regarding force opening the inspector!
> > 
> > 
> > Because it's already opened by default.
> 
> From what I can see in [this line](https://github.com/Atypon-OpenSource/manuscripts-article-editor/blob/master/src/components/projects/Inspector.tsx#L88), it currently depends on the existence of a suggestion or comment. Are these conditions met in your case?

yes, it meet the condition in my case. do we need to make it open even though there are no comments and suggestions?

**Comment by fwaisi** [comment]
> > > > @fwaisi, I see nothing regarding force opening the inspector!
> > > 
> > > 
> > > Because it's already opened by default.
> > 
> > 
> > From what I can see in [this line](https://github.com/Atypon-OpenSource/manuscripts-article-editor/blob/master/src/components/projects/Inspector.tsx#L88), it currently depends on the existence of a suggestion or comment. Are these conditions met in your case?
> 
> yes, it meet the condition in my case. do we need to make it open even though there are no comments and suggestions?

@IslamJMomani, I have added a comment on the ticket for Pans to advise on it.
thanks.

**Review by IslamJMomani — APPROVED** [review]
Approved! Just please recheck the package.json file before merging as it doesn't look right.

**Review by IslamJMomani — APPROVED** [review]

**Pull request merged**
