### PR TITLE
LTYP-110 - Support for bulleted lists (LEAN-3423)

### PR DESCRIPTION
**Pull request by asouqi**

### CODE REVIEW

**Review by mnatsheh — COMMENTED** [review]
Why can't we continue to use `useDropdown ` here?

**Comment by asouqi** [comment]
> Why can't we continue to use useDropdown here?

reverted to use dropdown hook so we could take advantage of the outside click to close the list, and the general `contextList` state will decide when to open /close the list, which will help to avoid opening both lists

**Comment by mnatsheh** [comment]
Shouldn't `useDropdown` automatically close the dropdown when the other dropdown is clicked? or am I missing something?

**Comment by asouqi** [comment]
> Shouldn't useDropdown automatically close the dropdown when the other dropdown is clicked? or am I missing something?

yes that is right, but when I test that locally the outside click listener will not be triggered just for the case of clicking on the second list option menu, if we click anywhere other than that place it's going to be triggered!!!

**Comment by asouqi** [comment]
> yes that is right, but when I test that locally the outside click listener will not be triggered just for the case of clicking on the second list option menu, if we click anywhere other than that place it's going to be triggered!!!

find the issue of that ignore, the stop of event [propagation](https://github.com/Atypon-OpenSource/manuscripts-style-guide/blob/master/src/hooks/use-dropdown.ts#L23) will not lead to the [outside](https://github.com/Atypon-OpenSource/manuscripts-style-guide/blob/master/src/hooks/use-dropdown.ts#L39C14-L39C30) click listener

**Review by mnatsheh — APPROVED** [review]

**Pull request merged**
